version: 2
sources:
  - name: dbt_reconfigured
    tables:
      - name: jaffle_customers
        columns:
          - name: id
            data_type: INT64
          - name: first_name
            data_type: STRING
          - name: last_name
            data_type: STRING

      - name: jaffle_orders
        columns:
          - name: id
            data_type: INT64
          - name: user_id
            data_type: INT64
          - name: order_date
            data_type: DATE
          - name: status
            data_type: STRING
          - name: _etl_loaded_at
            data_type: DATETIME

      - name: jaffle_payments
        columns:
          - name: id
            data_type: INT64
          - name: orderid
            data_type: INT64
          - name: paymentmethod
            data_type: STRING
          - name: status
            data_type: STRING
          - name: amount
            data_type: INT64
          - name: created
            data_type: DATE
          - name: _batched_at
            data_type: DATETIME
